# Base image
FROM python:3.10

# Set work directory
WORKDIR /app

# Copy files
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY src/ src/

# Expose port
EXPOSE 5000

# Run app
CMD ["python", "src/app.py"]
